name: My GitHub Actions Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build code
        run: echo "Building project..."

      - name: Test code
        run: echo "Running tests..."

      - name: Deploy
        run: echo "Deploying app..."
